name: Build

on: [workflow_dispatch]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-14]
        include:
          - os: ubuntu-latest
            target: linux-x64
          - os: windows-latest
            target: win-x64
          - os: macos-13
            target: osx-x64
          - os: macos-14
            target: osx-arm64
      fail-fast: false
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0

    - name: Build ${{ matrix.target }}
      run: dotnet publish Lizard.csproj --self-contained -p:DebugType=embedded -c release -p:PublishAOT=true -p:PublishSingleFile=false -p:DefineConstants="PUBLISH_AOT" -r ${{ matrix.target }} -o "${{ github.workspace }}/builds/${{ matrix.target }}"

    - name: Check Compiler
      run: ${{ github.workspace }}/builds/${{ matrix.target }}/Lizard compiler
      
    - name: Run Bench
      run: ${{ github.workspace }}/builds/${{ matrix.target }}/Lizard bench
      
    - name: Check crashlog.txt
      if: ${{ failure() }}
      run: cat ${{ github.workspace }}/builds/${{ matrix.target }}/crashlog.txt
      
    - name: Upload ${{ matrix.target }} Build
      uses: actions/upload-artifact@v3
      with:
        name: Lizard-${{ matrix.target }}
        path: ${{ github.workspace }}/builds/${{ matrix.target }}
