name: Build

on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
        - os: ubuntu-latest
          target: linux-x64
        - os: windows-latest
          target: win-x64
        - os: macos-latest
          target: osx-x64
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0

    - name: Build ${{ matrix.target }}
      run: dotnet publish Lizard.csproj --self-contained -p:DebugType=embedded -c release -r ${{ matrix.target }} -o "${{ github.workspace }}/builds/${{ matrix.target }}"

    - name: Where the honk is my file part1
      run: ls -la ${{ github.workspace }}

    - name: Where the honk is my file part2
      run: ls -la ${{ github.workspace }}/builds

    - name: Where the honk is my file part3
      run: ls -la ${{ github.workspace }}/builds/${{ matrix.target }}
      
    - name: Run Bench
      run: ${{ github.workspace }}/builds/${{ matrix.target }}/Lizard bench
      
    - name: Upload ${{ matrix.target }} Build
      uses: actions/upload-artifact@v3
      with:
        name: Lizard-${{ matrix.target }}
        path: ${{ github.workspace }}/builds/${{ matrix.target }}
